export interface ResourceReview {
  id: string;
  reviewerName: string;
  rating: number;
  date: string;
  comment: string;
}

export interface Resource {
  id: string;
  title: string;
  subject: string;
  type: 'pdf' | 'video' | 'notes' | 'practice-test';
  creator: string;
  price: number; // 0 for free
  rating: number;
  downloads: number;
  preview: string;
  isFeatured: boolean;
  category?: string;
  tags?: string[];
  reviewCount?: number;
  description?: string;
  reviews?: ResourceReview[];
  creatorRating?: number;
  creatorStudents?: number;
  bundleId?: string;
}

export interface ResourceBundle {
  id: string;
  title: string;
  description: string;
  resourceIds: string[];
  originalTotal: number;
  bundlePrice: number;
  savings: number;
  savingsPercent: number;
  creator: string;
  rating: number;
  reviewCount: number;
}

const mockReviews = [
  { id: 'rev-1', reviewerName: 'Ahmed R.', rating: 5, date: '2 days ago', comment: 'Excellent resource, very helpful!' },
  { id: 'rev-2', reviewerName: 'Fatima S.', rating: 4, date: '1 week ago', comment: 'Good quality, but could use more examples.' },
  { id: 'rev-3', reviewerName: 'Usman K.', rating: 5, date: '3 weeks ago', comment: 'Just what I needed to pass my exam.' }
];

export const resources: Resource[] = [
  {
    id: 'r-1',
    title: 'MDCAT Biology Full Syllabus Notes 2024',
    subject: 'MDCAT Biology',
    type: 'notes',
    creator: 'Dr. Tariq Mahmood',
    price: 1500,
    rating: 4.9,
    downloads: 5200,
    preview: 'Comprehensive notes covering PMC syllabus for Biology with diagrams.',
    isFeatured: true,
    category: 'Academic Exams',
    tags: ['mdcat', 'biology', 'medical'],
    reviewCount: 120,
    description: 'Master the MDCAT Biology syllabus with these comprehensive notes. Includes detailed diagrams, mnemonics, and summary sheets for quick revision.',
    reviews: mockReviews,
    creatorRating: 4.9,
    creatorStudents: 15000,
  },
  {
    id: 'r-2',
    title: 'O-Level Math Past Papers Topical (2015-2023)',
    subject: 'O-Level Math',
    type: 'pdf',
    creator: 'Sara Ali',
    price: 0,
    rating: 4.8,
    downloads: 12000,
    preview: 'Compiled topical past papers with marking schemes.',
    isFeatured: true,
    category: 'Academic Exams',
    tags: ['olevel', 'math', 'past-papers'],
    reviewCount: 340,
    description: 'Topical past papers for O-Level Mathematics from 2015 to 2023. Includes marking schemes for every question.',
    reviews: mockReviews,
    creatorRating: 4.8,
    creatorStudents: 22000,
  },
  {
    id: 'r-3',
    title: 'A-Level Economics Complete Crash Course',
    subject: 'A-Level Economics',
    type: 'video',
    creator: 'Zainab Sheikh',
    price: 2000,
    rating: 4.7,
    downloads: 850,
    preview: '10 hours of video content covering Micro and Macro economics concepts.',
    isFeatured: false,
    category: 'Academic Exams',
    tags: ['alevel', 'economics', 'video'],
    reviewCount: 45,
    description: 'A complete crash course on A-Level Economics. Covers both AS and A2 content, with a focus on graph analysis and essay writing.',
    reviews: mockReviews,
    creatorRating: 4.7,
    creatorStudents: 5000,
  },
  {
    id: 'r-4',
    title: 'ECAT Physics Grand Mock Test',
    subject: 'ECAT Physics',
    type: 'practice-test',
    creator: 'Muhammad Hassan',
    price: 500,
    rating: 4.6,
    downloads: 3000,
    preview: 'Simulation of UET ECAT exam with timed sections.',
    isFeatured: true,
    category: 'Academic Exams',
    tags: ['ecat', 'physics', 'engineering'],
    reviewCount: 210,
    description: 'A full-length mock test for the ECAT Physics section. Simulates the actual exam environment with timed sections and detailed solutions.',
    reviews: mockReviews,
    creatorRating: 4.5,
    creatorStudents: 8000,
  },
  {
    id: 'r-5',
    title: 'Organic Chemistry Flashcards',
    subject: 'MDCAT Chemistry',
    type: 'pdf',
    creator: 'Ayesha Siddiqui',
    price: 0,
    rating: 4.9,
    downloads: 8000,
    preview: 'Quick revision flashcards for all organic reactions.',
    isFeatured: true,
    category: 'Academic Exams',
    tags: ['mdcat', 'chemistry', 'flashcards'],
    reviewCount: 500,
    description: 'High-yield flashcards for organic chemistry. Perfect for memorizing reactions, mechanisms, and reagents.',
    reviews: mockReviews,
    creatorRating: 4.9,
    creatorStudents: 18000,
  },
  {
    id: 'r-6',
    title: 'DSA in C++: A Practical Guide',
    subject: 'DSA',
    type: 'notes',
    creator: 'Omar Farooq',
    price: 1200,
    rating: 4.8,
    downloads: 400,
    preview: 'Step-by-step implementation of data structures in C++.',
    isFeatured: false,
    category: 'Computer Science',
    tags: ['dsa', 'c++', 'programming'],
    reviewCount: 30,
    description: 'A comprehensive guide to Data Structures and Algorithms in C++. Includes code snippets, complexity analysis, and practice problems.',
    reviews: mockReviews,
    creatorRating: 4.8,
    creatorStudents: 2000,
  },
  {
    id: 'r-7',
    title: 'IELTS Band 8 Speaking Strategies',
    subject: 'IELTS Prep',
    type: 'video',
    creator: 'Amina Baig',
    price: 0,
    rating: 4.7,
    downloads: 4500,
    preview: 'Tips and tricks to score a Band 8+ in IELTS Speaking.',
    isFeatured: false,
    category: 'Languages',
    tags: ['ielts', 'english', 'speaking'],
    reviewCount: 150,
    description: 'Proven strategies to ace the IELTS speaking test. Includes sample answers, vocabulary lists, and common topics.',
    reviews: mockReviews,
    creatorRating: 4.6,
    creatorStudents: 12000,
  },
  {
    id: 'r-8',
    title: 'A-Level Math P1 Formula Sheet',
    subject: 'A-Level Math',
    type: 'pdf',
    creator: 'Bilal Ahmad',
    price: 0,
    rating: 4.9,
    downloads: 9200,
    preview: 'Essential formulas for Paper 1.',
    isFeatured: false,
    category: 'Academic Exams',
    tags: ['alevel', 'math', 'formula'],
    reviewCount: 400,
    description: 'A handy cheat sheet containing all the essential formulas for A-Level Mathematics Paper 1.',
    reviews: mockReviews,
    creatorRating: 4.9,
    creatorStudents: 25000,
  },
  {
    id: 'r-9',
    title: 'MDCAT Physics Numericals Bank',
    subject: 'MDCAT Physics',
    type: 'practice-test',
    creator: 'Ali Raza',
    price: 1000,
    rating: 4.5,
    downloads: 2100,
    preview: '500+ numerical problems specifically designed for MDCAT.',
    isFeatured: false,
    category: 'Academic Exams',
    tags: ['mdcat', 'physics', 'numericals'],
    reviewCount: 95,
    description: 'A massive bank of physics numerical problems tailored for the MDCAT. Includes step-by-step solutions.',
    reviews: mockReviews,
    creatorRating: 4.4,
    creatorStudents: 6000,
  },
  {
    id: 'r-10',
    title: 'Upwork Profile Optimization Guide',
    subject: 'Freelancing',
    type: 'notes',
    creator: 'Sana Qureshi',
    price: 800,
    rating: 4.8,
    downloads: 1500,
    preview: 'Learn how to rank your profile and win the first job.',
    isFeatured: false,
    category: 'Business & Career',
    tags: ['freelancing', 'upwork', 'career'],
    reviewCount: 110,
    description: 'A step-by-step guide to setting up a winning Upwork profile. Learn how to write proposals, set rates, and attract clients.',
    reviews: mockReviews,
    creatorRating: 4.8,
    creatorStudents: 4500,
  },
  // 12 NEW RESOURCES
  {
    id: 'r-11',
    title: 'MDCAT Chemistry Grand Mock',
    subject: 'MDCAT Chemistry',
    type: 'practice-test',
    creator: 'Dr. Tariq Mahmood',
    price: 600,
    rating: 4.7,
    downloads: 1800,
    preview: 'Full length mock exam for MDCAT Chemistry.',
    isFeatured: false,
    category: 'Academic Exams',
    tags: ['mdcat', 'chemistry', 'mock'],
    reviewCount: 65,
    description: 'Test your preparation with this full-length MDCAT Chemistry mock exam. Includes detailed explanations for all answers.',
    reviews: mockReviews,
    creatorRating: 4.9,
    creatorStudents: 15000,
  },
  {
    id: 'r-12',
    title: 'ECAT Math Quick Revision',
    subject: 'ECAT Math',
    type: 'pdf',
    creator: 'Muhammad Hassan',
    price: 300,
    rating: 4.6,
    downloads: 2200,
    preview: 'Short notes for ECAT Math concepts.',
    isFeatured: false,
    category: 'Academic Exams',
    tags: ['ecat', 'math', 'revision'],
    reviewCount: 88,
    description: 'Quick revision notes for ECAT Mathematics. Perfect for last-minute review.',
    reviews: mockReviews,
    creatorRating: 4.5,
    creatorStudents: 8000,
  },
  {
    id: 'r-13',
    title: 'O-Level Physics Topical Notes',
    subject: 'O-Level Physics',
    type: 'notes',
    creator: 'Sara Ali',
    price: 1000,
    rating: 4.8,
    downloads: 4000,
    preview: 'Detailed topical notes for O-Level Physics.',
    isFeatured: true,
    category: 'Academic Exams',
    tags: ['olevel', 'physics', 'notes'],
    reviewCount: 150,
    description: 'Comprehensive topical notes covering the entire O-Level Physics syllabus.',
    reviews: mockReviews,
    creatorRating: 4.8,
    creatorStudents: 22000,
  },
  {
    id: 'r-14',
    title: 'A-Level Chemistry Video Lectures',
    subject: 'A-Level Chemistry',
    type: 'video',
    creator: 'Zainab Sheikh',
    price: 2500,
    rating: 4.9,
    downloads: 1200,
    preview: 'Complete video series for A-Level Chemistry.',
    isFeatured: false,
    category: 'Academic Exams',
    tags: ['alevel', 'chemistry', 'video'],
    reviewCount: 90,
    description: 'In-depth video lectures covering AS and A2 Chemistry. Crystal clear explanations of complex topics.',
    reviews: mockReviews,
    creatorRating: 4.7,
    creatorStudents: 5000,
  },
  {
    id: 'r-15',
    title: 'OOP in Java Masterclass',
    subject: 'OOP',
    type: 'video',
    creator: 'Omar Farooq',
    price: 1500,
    rating: 4.8,
    downloads: 800,
    preview: 'Learn Object-Oriented Programming concepts in Java.',
    isFeatured: false,
    category: 'Computer Science',
    tags: ['oop', 'java', 'programming'],
    reviewCount: 55,
    description: 'Master Object-Oriented Programming principles using Java. Covers inheritance, polymorphism, encapsulation, and more.',
    reviews: mockReviews,
    creatorRating: 4.8,
    creatorStudents: 2000,
  },
  {
    id: 'r-16',
    title: 'Data Structures Interview Prep',
    subject: 'DSA',
    type: 'pdf',
    creator: 'Omar Farooq',
    price: 800,
    rating: 4.7,
    downloads: 1100,
    preview: 'Top 100 DSA questions asked in tech interviews.',
    isFeatured: true,
    category: 'Computer Science',
    tags: ['dsa', 'interview', 'tech'],
    reviewCount: 70,
    description: 'A curated list of the top 100 Data Structures and Algorithms questions frequently asked in technical interviews.',
    reviews: mockReviews,
    creatorRating: 4.8,
    creatorStudents: 2000,
  },
  {
    id: 'r-17',
    title: 'Fiverr Success Blueprint',
    subject: 'Freelancing',
    type: 'notes',
    creator: 'Sana Qureshi',
    price: 1000,
    rating: 4.6,
    downloads: 1300,
    preview: 'How to create gigs that sell on Fiverr.',
    isFeatured: false,
    category: 'Business & Career',
    tags: ['fiverr', 'freelancing', 'career'],
    reviewCount: 80,
    description: 'Learn the secrets of successful Fiverr sellers. From gig creation to SEO optimization and client communication.',
    reviews: mockReviews,
    creatorRating: 4.8,
    creatorStudents: 4500,
  },
  {
    id: 'r-18',
    title: 'Resume Writing for Tech Jobs',
    subject: 'Career Guidance',
    type: 'pdf',
    creator: 'Hassan Raza',
    price: 0,
    rating: 4.9,
    downloads: 5000,
    preview: 'Templates and tips for tech resumes.',
    isFeatured: false,
    category: 'Business & Career',
    tags: ['resume', 'tech', 'career'],
    reviewCount: 200,
    description: 'Stand out to recruiters with these ATS-friendly tech resume templates and writing tips.',
    reviews: mockReviews,
    creatorRating: 4.9,
    creatorStudents: 10000,
  },
  {
    id: 'r-19',
    title: 'Digital Marketing Fundamentals',
    subject: 'Digital Marketing',
    type: 'video',
    creator: 'Ali Khan',
    price: 1800,
    rating: 4.5,
    downloads: 900,
    preview: 'Introduction to SEO, SEM, and Social Media Marketing.',
    isFeatured: false,
    category: 'Marketing',
    tags: ['marketing', 'seo', 'social-media'],
    reviewCount: 40,
    description: 'Learn the basics of digital marketing, including search engine optimization, pay-per-click advertising, and social media strategy.',
    reviews: mockReviews,
    creatorRating: 4.5,
    creatorStudents: 3000,
  },
  {
    id: 'r-20',
    title: 'Personal Finance for Students',
    subject: 'Personal Finance',
    type: 'notes',
    creator: 'Zara Ahmed',
    price: 500,
    rating: 4.8,
    downloads: 2500,
    preview: 'Budgeting, saving, and investing basics for college students.',
    isFeatured: true,
    category: 'Finance',
    tags: ['finance', 'budgeting', 'students'],
    reviewCount: 120,
    description: 'A practical guide to managing money as a student. Learn how to budget, save, and start investing early.',
    reviews: mockReviews,
    creatorRating: 4.8,
    creatorStudents: 8000,
  },
  {
    id: 'r-21',
    title: 'Urdu Essay Writing Tips',
    subject: 'Urdu',
    type: 'pdf',
    creator: 'Ahmad Ali',
    price: 0,
    rating: 4.7,
    downloads: 3200,
    preview: 'How to structure and write high-scoring Urdu essays.',
    isFeatured: false,
    category: 'Languages',
    tags: ['urdu', 'essay', 'writing'],
    reviewCount: 90,
    description: 'Improve your Urdu essay writing skills with these structural templates and vocabulary enhancements.',
    reviews: mockReviews,
    creatorRating: 4.7,
    creatorStudents: 5000,
  },
  {
    id: 'r-22',
    title: 'Intro to Machine Learning',
    subject: 'AI/ML',
    type: 'video',
    creator: 'Dr. Usman',
    price: 3000,
    rating: 4.9,
    downloads: 1500,
    preview: 'Beginner friendly guide to ML algorithms.',
    isFeatured: true,
    category: 'AI & Technology',
    tags: ['ai', 'ml', 'machine-learning'],
    reviewCount: 110,
    description: 'A comprehensive introduction to Machine Learning. Covers supervised and unsupervised learning algorithms with Python examples.',
    reviews: mockReviews,
    creatorRating: 4.9,
    creatorStudents: 12000,
  }
];

export const bundles: ResourceBundle[] = [
  {
    id: 'b-1',
    title: 'MDCAT Complete Prep Bundle',
    description: 'Everything you need to ace MDCAT 2026 — Biology notes, Chemistry flashcards, Physics numericals, and a grand mock test in one discounted bundle.',
    resourceIds: ['r-1', 'r-5', 'r-9', 'r-4'],
    originalTotal: 4000,
    bundlePrice: 2800,
    savings: 1200,
    savingsPercent: 30,
    creator: 'Dr. Tariq Mahmood',
    rating: 4.9,
    reviewCount: 87,
  },
  {
    id: 'b-2',
    title: 'Tech Career Starter Pack',
    description: 'From DSA basics to Upwork success — master the technical and freelancing skills needed to launch your tech career.',
    resourceIds: ['r-6', 'r-10', 'r-15', 'r-16'],
    originalTotal: 4300,
    bundlePrice: 2800,
    savings: 1500,
    savingsPercent: 35,
    creator: 'Omar Farooq',
    rating: 4.7,
    reviewCount: 43,
  },
];
