export interface Tutor {
  id: string;
  name: string;
  avatarUrl: string;
  subjects: string[];
  rating: number;
  reviews: number;
  hourlyRate: number;
  isVerified: boolean;
  isTopTutor: boolean;
  isFeatured: boolean;
  sessionFormat: 'online' | 'in-person' | 'both';
  location: string;
  bio: string;
  totalStudents: number;
  yearsExperience: number;
  languages: string[];
  availability: string;
}

export const tutors: Tutor[] = [
  {
    id: 't-1',
    name: 'Ahmed Khan',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed%20Khan',
    subjects: ['MDCAT Biology', 'MDCAT Chemistry'],
    rating: 4.9,
    reviews: 150,
    hourlyRate: 1500,
    isVerified: true,
    isTopTutor: true,
    isFeatured: true,
    sessionFormat: 'both',
    location: 'Lahore',
    bio: 'Experienced MDCAT instructor with a track record of producing top scorers. Specializing in Biology and Chemistry.',
    totalStudents: 300,
    yearsExperience: 8,
    languages: ['Urdu', 'English'],
    availability: 'Next available slot: Today, 6:00 PM',
  },
  {
    id: 't-2',
    name: 'Sara Ali',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sara%20Ali',
    subjects: ['O-Level Math', 'O-Level Physics'],
    rating: 4.8,
    reviews: 85,
    hourlyRate: 1200,
    isVerified: true,
    isTopTutor: false,
    isFeatured: true,
    sessionFormat: 'online',
    location: 'Karachi',
    bio: 'Passionate about making Math and Physics easy to understand for O-Level students. Focus on past papers and concept building.',
    totalStudents: 120,
    yearsExperience: 4,
    languages: ['Urdu', 'English'],
    availability: 'Next available slot: Tomorrow, 4:00 PM',
  },
  {
    id: 't-3',
    name: 'Muhammad Hassan',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Muhammad%20Hassan',
    subjects: ['ECAT Math', 'ECAT Physics'],
    rating: 5.0,
    reviews: 400,
    hourlyRate: 2000,
    isVerified: true,
    isTopTutor: true,
    isFeatured: true,
    sessionFormat: 'both',
    location: 'Islamabad',
    bio: 'UET graduate helping pre-engineering students achieve their dream university. Intensive problem-solving approach.',
    totalStudents: 500,
    yearsExperience: 10,
    languages: ['Urdu', 'English'],
    availability: 'Next available slot: Friday, 5:00 PM',
  },
  {
    id: 't-4',
    name: 'Fatima Malik',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima%20Malik',
    subjects: ['A-Level Biology', 'English'],
    rating: 4.7,
    reviews: 60,
    hourlyRate: 1800,
    isVerified: true,
    isTopTutor: false,
    isFeatured: false,
    sessionFormat: 'online',
    location: 'Rawalpindi',
    bio: 'Dedicated tutor for A-Level students. I provide comprehensive notes and conduct regular mock assessments.',
    totalStudents: 80,
    yearsExperience: 5,
    languages: ['Urdu', 'English'],
    availability: 'Next available slot: Saturday, 10:00 AM',
  },
  {
    id: 't-5',
    name: 'Usman Raza',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Usman%20Raza',
    subjects: ['Computer Science', 'OOP'],
    rating: 4.6,
    reviews: 50,
    hourlyRate: 1000,
    isVerified: false,
    isTopTutor: false,
    isFeatured: false,
    sessionFormat: 'online',
    location: 'Lahore',
    bio: 'Software Engineer turning students into coders. Learn OOP in C++ or Java with practical examples.',
    totalStudents: 45,
    yearsExperience: 2,
    languages: ['Urdu', 'English'],
    availability: 'Next available slot: Today, 8:00 PM',
  },
  {
    id: 't-6',
    name: 'Zainab Sheikh',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Zainab%20Sheikh',
    subjects: ['A-Level Economics', 'O-Level Math'],
    rating: 4.9,
    reviews: 110,
    hourlyRate: 1600,
    isVerified: true,
    isTopTutor: true,
    isFeatured: false,
    sessionFormat: 'both',
    location: 'Karachi',
    bio: 'Economics made simple. Real-world applications to help you ace your Cambridge exams.',
    totalStudents: 150,
    yearsExperience: 6,
    languages: ['Urdu', 'English'],
    availability: 'Next available slot: Monday, 3:00 PM',
  },
  {
    id: 't-7',
    name: 'Ali Raza',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ali%20Raza',
    subjects: ['MDCAT Physics', 'O-Level Physics'],
    rating: 4.5,
    reviews: 75,
    hourlyRate: 1200,
    isVerified: true,
    isTopTutor: false,
    isFeatured: false,
    sessionFormat: 'in-person',
    location: 'Islamabad',
    bio: 'Physics is all about concepts. I ensure my students build a strong foundation before jumping to complex problems.',
    totalStudents: 90,
    yearsExperience: 3,
    languages: ['Urdu'],
    availability: 'Next available slot: Tomorrow, 5:00 PM',
  },
  {
    id: 't-8',
    name: 'Nadia Hussain',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nadia%20Hussain',
    subjects: ['English', 'A-Level Economics'],
    rating: 4.8,
    reviews: 95,
    hourlyRate: 1400,
    isVerified: true,
    isTopTutor: false,
    isFeatured: false,
    sessionFormat: 'online',
    location: 'Lahore',
    bio: 'Improve your English fluency and economics concepts with tailored, interactive sessions.',
    totalStudents: 110,
    yearsExperience: 5,
    languages: ['Urdu', 'English'],
    availability: 'Next available slot: Thursday, 2:00 PM',
  },
  {
    id: 't-9',
    name: 'Omar Farooq',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Omar%20Farooq',
    subjects: ['DSA', 'Computer Science'],
    rating: 4.9,
    reviews: 200,
    hourlyRate: 1800,
    isVerified: true,
    isTopTutor: true,
    isFeatured: false,
    sessionFormat: 'online',
    location: 'Karachi',
    bio: 'Master Data Structures and Algorithms. Great for university students and technical interview prep.',
    totalStudents: 250,
    yearsExperience: 7,
    languages: ['Urdu', 'English'],
    availability: 'Next available slot: Today, 9:00 PM',
  },
  {
    id: 't-10',
    name: 'Ayesha Siddiqui',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ayesha%20Siddiqui',
    subjects: ['MDCAT Chemistry', 'O-Level Chemistry'],
    rating: 4.7,
    reviews: 88,
    hourlyRate: 1300,
    isVerified: true,
    isTopTutor: false,
    isFeatured: false,
    sessionFormat: 'both',
    location: 'Rawalpindi',
    bio: 'Chemistry can be fun! I use visual aids and mnemonic techniques to help you memorize complex reactions.',
    totalStudents: 100,
    yearsExperience: 4,
    languages: ['Urdu', 'English'],
    availability: 'Next available slot: Tomorrow, 11:00 AM',
  },
  {
    id: 't-11',
    name: 'Bilal Ahmad',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bilal%20Ahmad',
    subjects: ['A-Level Math', 'ECAT Math'],
    rating: 4.8,
    reviews: 130,
    hourlyRate: 1700,
    isVerified: true,
    isTopTutor: true,
    isFeatured: false,
    sessionFormat: 'online',
    location: 'Islamabad',
    bio: 'Experienced Math tutor specializing in competitive exams and Cambridge syllabus. Let\'s conquer math anxiety.',
    totalStudents: 180,
    yearsExperience: 6,
    languages: ['Urdu', 'English'],
    availability: 'Next available slot: Wednesday, 4:00 PM',
  },
  {
    id: 't-12',
    name: 'Mariam Tahir',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mariam%20Tahir',
    subjects: ['MDCAT Biology', 'A-Level Biology'],
    rating: 4.6,
    reviews: 55,
    hourlyRate: 1100,
    isVerified: false,
    isTopTutor: false,
    isFeatured: false,
    sessionFormat: 'in-person',
    location: 'Lahore',
    bio: 'Recent medical graduate providing up-to-date guidance on MDCAT prep. I know exactly what it takes to pass.',
    totalStudents: 60,
    yearsExperience: 1,
    languages: ['Urdu', 'English'],
    availability: 'Next available slot: Today, 5:00 PM',
  }
];
